/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.*;

/**
 *
 * @author deivi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        cbxurg = new javax.swing.JComboBox<>();
        txtedad = new javax.swing.JTextField();
        btntiquet = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jSpinnerasuntos = new javax.swing.JSpinner();
        txtcantickets = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblver = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setText("Condiciones Especiales");
        jTextField1.setAutoscrolls(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, -1));

        cbxurg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "Embarazada", "Niño en brazos", "Ninguno de los anteriores" }));
        jPanel1.add(cbxurg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        txtedad.setAutoscrolls(false);
        jPanel1.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 50, -1));

        btntiquet.setText("Generar Tiquete");
        btntiquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntiquetActionPerformed(evt);
            }
        });
        jPanel1.add(btntiquet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setText("Cantidad de Tickets ");
        jTextField3.setAutoscrolls(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 540, -1, -1));
        jPanel1.add(jSpinnerasuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 50, -1));

        txtcantickets.setEditable(false);
        txtcantickets.setAutoscrolls(false);
        jPanel1.add(txtcantickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 30, -1));

        jTextField5.setEditable(false);
        jTextField5.setText("Digite su edad");
        jTextField5.setAutoscrolls(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, -1));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generador de Tickets");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setText("Cantidad de Transacciones");
        jTextField6.setAutoscrolls(false);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, -1));

        tblver.setBackground(java.awt.SystemColor.control);
        tblver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Edad", "Condicion", "Cant. Transacciones", "Tiquete"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblver);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 470, 180));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cataratajpg.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -118, -1, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntiquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntiquetActionPerformed
        // TODO add your handling code here:
        Codigo.guardar(txtedad, cbxurg, jSpinnerasuntos, txtcantickets, tblver);
        
    }//GEN-LAST:event_btntiquetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntiquet;
    private javax.swing.JComboBox<String> cbxurg;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerasuntos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tblver;
    private javax.swing.JTextField txtcantickets;
    private javax.swing.JTextField txtedad;
    // End of variables declaration//GEN-END:variables
}
